apiVersion: v1
kind: ServiceAccount
metadata:
  name: cli-job-sa
  namespace: testing
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cli-job-sa-testing-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cli-job-sa
    namespace: testing
---
apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
  namespace: testing
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30
      containers:
        - image: registry.redhat.io/openshift4/ose-tools-rhel8:latest 
          # ref: https://catalog.redhat.com/software/containers/openshift4/ose-cli/5cd9ba3f5a13467289f4d51d?tag=v4.12.0-202307071529.p0.gea7c11a.assembly.stream&push_date=1689729113000
          name: testjob
          command:
            - /bin/bash
            - -c
            - |
              while true; do echo "hello"; sleep 10; done
